# Generated by Django 5.0.6 on 2024-07-06 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.CharField(max_length=9)),
                ('batchid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=4)),
                ('courseid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.IntegerField()),
                ('examtype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PaperMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papercode', models.CharField(max_length=8)),
                ('papertype', models.CharField(max_length=15)),
                ('papershtname', models.CharField(max_length=15)),
                ('papername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=3)),
                ('semid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studregno', models.IntegerField()),
                ('studname', models.CharField(max_length=25)),
                ('batchno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batchmaster')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursemaster')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semmaster')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInternalTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('batchno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batchmaster')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursemaster')),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exammaster')),
                ('papercode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.papermaster')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semmaster')),
                ('studregno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmaster')),
            ],
        ),
    ]
