# Generated by Django 5.0.6 on 2024-07-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papermaster',
            name='papertype',
            field=models.CharField(max_length=20),
        ),
    ]
