# Generated by Django 5.0.6 on 2024-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_papermaster_papertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batchid',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='batchno',
            field=models.IntegerField(),
        ),
    ]
