# Generated by Django 5.0.6 on 2024-07-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_batchmaster_batchid_alter_batchmaster_batchno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchMaster',
            new_name='BatchMasterModel',
        ),
        migrations.RenameModel(
            old_name='CourseMaster',
            new_name='CourseMasterModel',
        ),
        migrations.RenameModel(
            old_name='ExamMaster',
            new_name='ExamMasterModel',
        ),
        migrations.RenameModel(
            old_name='PaperMaster',
            new_name='PaperMasterModel',
        ),
        migrations.RenameModel(
            old_name='SemMaster',
            new_name='SemMasterModel',
        ),
        migrations.RenameModel(
            old_name='StudentInternalTrans',
            new_name='StudentInternalTransModel',
        ),
        migrations.RenameModel(
            old_name='StudentMaster',
            new_name='StudentMasterModel',
        ),
    ]
