# Generated by Django 5.0.6 on 2024-07-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentinternaltransmodel_studname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinternaltransmodel',
            name='studname',
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studregno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel'),
        ),
    ]
