# Generated by Django 5.0.6 on 2024-07-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_papercode_studentinternaltransmodel_papername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmastermodel',
            old_name='batchno',
            new_name='batchid',
        ),
    ]
