# Generated by Django 5.0.6 on 2024-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_batchno_studentmastermodel_batchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinternaltransmodel',
            old_name='batchno',
            new_name='batchid',
        ),
    ]
