# Generated by Django 5.0.6 on 2024-07-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_batchno_studentinternaltransmodel_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmastermodel',
            name='batchid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batchmastermodel',
            name='batchno',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='exammastermodel',
            name='examtype',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='papermastermodel',
            name='papershtname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='papermastermodel',
            name='papertype',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='studentmastermodel',
            name='studname',
            field=models.CharField(max_length=30),
        ),
    ]
