# Generated by Django 5.0.6 on 2024-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_studregno_studentinternaltransmodel_studname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmastermodel',
            name='batchid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='batchmastermodel',
            name='batchno',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='coursemastermodel',
            name='course',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='coursemastermodel',
            name='courseid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exammastermodel',
            name='examid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exammastermodel',
            name='examtype',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='papermastermodel',
            name='papercode',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='papermastermodel',
            name='papername',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='papermastermodel',
            name='papershtname',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='semmastermodel',
            name='sem',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='semmastermodel',
            name='semid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentmastermodel',
            name='studregno',
            field=models.IntegerField(unique=True),
        ),
    ]
