# Generated by Django 5.0.6 on 2024-07-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_batchmastermodel_batchid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinternaltransmodel',
            old_name='batchid',
            new_name='batchno',
        ),
        migrations.RenameField(
            model_name='studentmastermodel',
            old_name='batchid',
            new_name='batchno',
        ),
    ]
