# Generated by Django 5.0.6 on 2024-08-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_batchid_studentinternaltransmodel_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='batchno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batchmastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursemastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='examtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.exammastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='papername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.papermastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semmastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel', unique=True),
        ),
    ]
