# Generated by Django 5.0.6 on 2024-08-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_studentinternaltransmodel_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel', unique=True),
        ),
    ]
