# Generated by Django 5.0.6 on 2024-08-02 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_studentinternaltransmodel_studname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel'),
        ),
    ]
