# Generated by Django 5.0.6 on 2024-08-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_studentinternaltransmodel_studname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='marks',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='papername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.papermastermodel'),
        ),
    ]
