# Generated by Django 5.0.6 on 2024-08-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_studentinternaltransmodel_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='studentinternaltransmodel',
            unique_together={('studname', 'papername')},
        ),
    ]
