# Generated by Django 5.0.6 on 2024-08-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_studentinternaltransmodel_marks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinternaltransmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='papername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.papermastermodel', unique=True),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel', unique=True),
        ),
    ]
