# Generated by Django 5.0.6 on 2024-08-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_studentinternaltransmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='papername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.papermastermodel'),
        ),
        migrations.AlterField(
            model_name='studentinternaltransmodel',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmastermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinternaltransmodel',
            unique_together={('studname', 'papername')},
        ),
    ]
