# Generated by Django 5.0.6 on 2024-08-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_studentinternaltransmodel_papername_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinternaltransmodel',
            unique_together={('course', 'batchno', 'sem', 'examtype', 'studname', 'papername', 'marks')},
        ),
    ]
