# Generated by Django 5.0.6 on 2024-08-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_studentinternaltransmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinternaltransmodel',
            unique_together=set(),
        ),
    ]
